PLATFORM_YOUTUBE = "youtube"
PLATFORM_INSTAGRAM = "instagram"
PLATFORM_FACEBOOK = "facebook"
PLATFORM_TIKTOK = "tiktok"
ALL_PLATFORMS = [PLATFORM_YOUTUBE, PLATFORM_INSTAGRAM, PLATFORM_FACEBOOK, PLATFORM_TIKTOK]
