TYPE_TITLE = "title"
TYPE_CAPTION = "caption"
TYPE_HOOK = "hook"
TYPE_HASHTAG = "hashtag"
TYPE_THUMBNAIL = "thumbnail_concept"
TYPE_POSTING_TIME = "posting_time"
TYPE_CALENDAR = "content_calendar"
ALL_SUGGESTION_TYPES = [TYPE_TITLE, TYPE_CAPTION, TYPE_HOOK, TYPE_HASHTAG, TYPE_THUMBNAIL, TYPE_POSTING_TIME, TYPE_CALENDAR]
